### ISSUE TITLE
v1.4.0 Changelog

### ISSUE THREAD

**Issue by NYPD** [NYPD/ritsu.js#110]
## Changes
- #109 Deprecated getErrorMessagesAsMap as it didn't even work and could not work they way originally intended
- #109 Added new  getErrorMessagesAsObjects method as a substitute for getErrorMessagesAsMap

## Wiki
- [x] Add deprecation note for getErrorMessagesAsMap method
- [x] Add new entry for  getErrorMessagesAsObjects method
- [x] Add entry for previous deprecated resetIntialFormValues method
- [x] Perhaps add section for deprecated fields
