### ISSUE TITLE
v1.2.0 Changelog

### ISSUE THREAD

**Issue by NYPD** [NYPD/ritsu.js#67]
## Changes
- #66 Added ability to pass in a query string selector to all methods rather than just a jQuery object or element node
- #55
  -  Added functionality to reset form inputs to their initial values from when the `storeInitialValues()` was ran.
  - Added functionality to retrieve the initial value of a single input element
- #61 
  - `initialize()` now takes a messageCallback function
  - `validate()` now takes a messageCallback function
  - `showErrorMessages()` now takes a messageCallback function
  - new method to get an error message for a particular input 
  - new method to get error messages for several inputs
  - new method to get error messages for several inputs as a "map"
- #71 Added version variable to the ritsu library

## Fixes
- #69 When not using bootstrap styles, ritsu now removes previous error labels rather than leaving them there
- #75 **(Severe)** Two different copies of the rules object were present in ritsu leading to some unexpected behaviors

## Wiki
- [x] Add how one can use query selectors now when calling methods
- [x] Add entry on how initial values are stored in the `storeInitialValues()`
- [x] Add getInitialFormValue() method entry
- [x] Add resetIntialFormValues() method entry
- [x] Add entry on new messageCallback property in `initialize()`
- [x] Add how one can reset all options to default in `initialize()` when calling it with a empty object
- [x] Add new signature for the `initialize()` method to take a messageCallback function
- [x] Add new signature for the `validate()` method to take a messageCallback function
- [x] Add new signature for the `showErrorMessages()` method to take a messageCallback function
- [x] Add new method entry `getErrorMessage()`
- [x] Add new method entry `getErrorMessages()`
- [x] Add new method entry `getErrorMessagesAsMap()`
